all:
  vars:
    ansible_user: <bootstrap-user>
    ansible_python_interpreter: auto_silent
  children:
    edge_nodes:
      hosts:
        edge-01:
          ansible_host: <edge-floating-ip>
    api_lb:
      vars:
        ansible_ssh_common_args: "-o ProxyJump=<bootstrap-user>@<edge-floating-ip>"
      hosts:
        api-lb-01:
          ansible_host: <api-lb-private-ip>
    control_plane:
      vars:
        ansible_ssh_common_args: "-o ProxyJump=<bootstrap-user>@<edge-floating-ip>"
      hosts:
        k8s-cp-01:
          ansible_host: <cp-private-ip>
    workers:
      vars:
        ansible_ssh_common_args: "-o ProxyJump=<bootstrap-user>@<edge-floating-ip>"
      hosts:
        k8s-worker-01:
          ansible_host: <worker1-private-ip>
        k8s-worker-02:
          ansible_host: <worker2-private-ip>
